### ISSUE TITLE
Extension Data Collection Feedback

### ISSUE THREAD

**Issue by jpmarcotte** [jpmarcotte/HeroesDraftHelper#11]
Should find a checkbox for the buttons that signify when the data has been accurately saved.

**Comment by jpmarcotte** [comment]
I wouldn't mind making the buttons on the various pages look more like the buttons on the popup. I'd also like the ability to add a class to them that would display a check-mark icon on them (kind of like the download icon in the popup) after the data has been stored.

Think you could let me know what changes would need to be made? I think I know how to implement the logic to do the updating after the storage has succeeded.

**Comment by jpmarcotte** [comment]
Perhaps even come up with some icons (and tooltips) for various states:
- No data stored
- Data stored, but probably old
- Data stored, and probably fresh
- Data successfully updated just now.

**Comment by shoemakn** [comment]
All of the ones here on the “Halflings” tab are already pre-configured via Bootstrap: http://glyphicons.com/ http://glyphicons.com/

If these aren’t enough, it’s quite easy to use FontAwesome instead (http://fontawesome.io/icons/ http://fontawesome.io/icons/)

— Nick Shoemaker

**Comment by jpmarcotte** [comment]
This got taken care of.
